### ISSUE TITLE
Link to Doug Ashton's talk at BristolR

### ISSUE THREAD

**Issue by wlandau** [ropensci-books/drake#132]
@dougmet, may I link to your BristolR talk [here](https://books.ropensci.org/drake/index.html#presentations)? And would you be willing to share the materials?

**Comment by dougmet** [comment]
Absolutely. I'm a little embarrassed because the kaggle project to demo it all isn't really finished (summer was much busier than I expected!) but enough of the drake infrastructure is in to make it interesting. I'll get the material added to the gitlab repo (or maybe convert to Google Slides) and PR the link if that's easier.

At the BristolR meetup loads of people were talking about how they were using drake and there was a lot of buzz about it. Thanks so much for really nailing it with this package!

The not-done-yet project is here https://gitlab.com/dougmet/rapid-repro

**Comment by wlandau** [comment]
Awesome, thanks Doug! A PR would be super helpful when you are ready.

**Comment by wlandau** [comment]
@dougmet, any update on when you might be ready for a reference in `drake`'s manual?

**Comment by dougmet** [comment]
Hi @wlandau , sincere apologies. I'll update in the next week or two (if it's not too late). I'm restoring the project on a new computer (Drake has been fine but the md5 of the kaggle data changed for some reason) so it adds a nice little story at the end. Apologies again. I'll set regular reminders until I've done it!

**Comment by wlandau** [comment]
Thanks for the update, please let me know when you are ready. No rush.

**Comment by wlandau** [comment]
This issue has been up for a while, so I am closing it. @dougmet, I would still be happy to link to your talk in the docs. Just let me know if/when you are ready.

**Comment by dougmet** [comment]
Hi @wlandau yeah totally fair. Really sorry I've just not found the time. Will let you know if I get it sorted.
